//! HMAC, key derivation and authenticated encryption.
//!
//! # What this module protects
//!
//! Until phase 8, the seed of a Q21 wallet lived **in the clear** in
//! `wallet.dat`, as sixty-four hexadecimal characters. Anyone who had read
//! this file once — a backup, a resold disk, a curious process, a network
//! share — held the funds for good. There was no password, and nothing said
//! so.
//!
//! # What is not built here
//!
//! No new primitive. Everything below is built **on top of SHA-256**, whose
//! implementation is checked against the official FIPS 180-4 vectors:
//!
//! - **HMAC-SHA256** (RFC 2104), checked against the RFC 4231 vectors;
//! - **PBKDF2-HMAC-SHA256** (RFC 8018), which is just repeated HMAC;
//! - a **keystream** generated by HMAC in counter mode, then
//!   **authenticated separately** (encrypt-then-authenticate).
//!
//! Inventing a block cipher would be the same mistake as inventing a
//! lattice-based signature scheme. Composing standard constructions on top of
//! a proven hash function is not: it is what HKDF, PBKDF2 and CTR mode have
//! done for thirty years.
//!
//! # Key derivation: Argon2id
//!
//! The first version derived the key with PBKDF2, and said so plainly:
//! PBKDF2 is not memory-hard, and an attacker equipped with dedicated
//! circuits tests passphrases much faster than a processor. The only defense
//! was the length of the passphrase.
//!
//! The derivation is now **Argon2id** ([`crate::argon2`], RFC 9106): 64 MiB
//! of memory and three passes per attempt, which costs a dedicated circuit
//! roughly what it costs the user — a third of a second on a desktop
//! processor, one second on a Raspberry Pi. It is not a primitive invented
//! here: it is the standard, implemented from its text and checked against
//! its three vectors, as SHA-256 is against FIPS 180-4.
//!
//! # Formats
//!
//! | Format | Derivation | Keystream label | Status |
//! |---|---|---|---|
//! | 1 | PBKDF2 | legacy | read, never written |
//! | 2 | Argon2id | legacy | read, never written (0.3.x) |
//! | 3 | Argon2id | `Q21/keystream` | written since 0.4 |
//!
//! Formats 3 and 2 differ only by their magic and the keystream label: 0.4
//! renamed the label, and a new label needs a new magic, or a file could not
//! say which label it was sealed under. The magics and the label of formats 1
//! and 2 live in [`crate::legacy`]. An older file is resealed in format 3 at
//! its next write, which happens as soon as the first address is drawn or the
//! first spend is made.

use crate::sha256::{sha256, Sha256};

/// SHA-256 block size, in bytes. It is what governs HMAC.
const HASH_BLOCK: usize = 64;

/// PBKDF2 iterations of files in format 1.
///
/// Only used to read them back and by the tests; new files are sealed with
/// Argon2id using [`DEFAULT_COST`].
pub const DEFAULT_ITERATIONS: u32 = 600_000;

/// Cost of an Argon2id derivation: memory and passes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Cost {
    pub memory_kib: u32,
    pub passes: u32,
}

/// The default cost: 64 MiB, three passes, one lane.
///
/// This is the "conservative" setting of RFC 9106 for interactive use.
/// Measured: 0.30 s on a small server processor, so less on a PC and about
/// one second on a Raspberry Pi — less than the 600,000 PBKDF2 iterations it
/// replaces, for an incomparably stronger resistance to dedicated hardware.
pub const DEFAULT_COST: Cost = Cost {
    memory_kib: 64 * 1024,
    passes: 3,
};

/// The test cost: the same algorithm, in a fraction of a second.
pub const TEST_COST: Cost = Cost {
    memory_kib: 64,
    passes: 1,
};

/// Ceilings accepted on reading, for the same reasons as
/// [`MAX_ITERATIONS`]: a rewritten header must not be able to impose a huge
/// allocation and minutes of computation before any rejection.
///
/// The parameters are read **before** checking the MAC — they have to be, to
/// derive the key — so it is this bound, and it alone, that limits what a
/// rewritten file costs on opening. Four times the default setting in
/// memory, a little over three times in passes: enough for a strengthened
/// setting, not for a one-gibibyte allocation which, on a small machine,
/// killed the process before the authentication failure.
pub const MAX_MEMORY_KIB: u32 = 256 * 1024;
pub const MAX_PASSES: u32 = 10;

/// HMAC-SHA256, as described by RFC 2104.
pub fn hmac_sha256(key: &[u8], message: &[u8]) -> [u8; 32] {
    // A key longer than a block is hashed first. A shorter key is padded
    // with zeros. That is the definition, and forgetting it silently breaks
    // interoperability.
    let mut k = [0u8; HASH_BLOCK];
    if key.len() > HASH_BLOCK {
        k[..32].copy_from_slice(&sha256(key));
    } else {
        k[..key.len()].copy_from_slice(key);
    }

    let mut ipad = [0x36u8; HASH_BLOCK];
    let mut opad = [0x5cu8; HASH_BLOCK];
    for i in 0..HASH_BLOCK {
        ipad[i] ^= k[i];
        opad[i] ^= k[i];
    }

    let mut inner = Sha256::new();
    inner.update(&ipad);
    inner.update(message);
    let h1 = inner.finalize();

    let mut outer = Sha256::new();
    outer.update(&opad);
    outer.update(&h1);
    outer.finalize()
}

/// PBKDF2-HMAC-SHA256, as described by RFC 8018.
///
/// Returns `out.len()` bytes derived from `password` and `salt`.
///
/// # Panics
///
/// If `iterations` is zero. A derivation without iterations would be a mere
/// HMAC disguised as protection, which is worse than no protection.
pub fn pbkdf2(password: &[u8], salt: &[u8], iterations: u32, out: &mut [u8]) {
    assert!(iterations > 0, "PBKDF2 without iterations");

    let mut block_index: u32 = 1;
    let mut written = 0usize;

    while written < out.len() {
        // U1 = HMAC(password, salt || INT_32_BE(i))
        let mut input = Vec::with_capacity(salt.len() + 4);
        input.extend_from_slice(salt);
        input.extend_from_slice(&block_index.to_be_bytes());

        let mut u = hmac_sha256(password, &input);
        let mut t = u;
        for _ in 1..iterations {
            u = hmac_sha256(password, &u);
            for i in 0..32 {
                t[i] ^= u[i];
            }
        }

        let n = (out.len() - written).min(32);
        out[written..written + n].copy_from_slice(&t[..n]);
        written += n;
        block_index += 1;
    }
}

/// Keystream: HMAC in counter mode.
///
/// `byte[i]` of the stream is the corresponding byte of
/// `HMAC(key, label || counter)`, the label being [`KEYSTREAM_LABEL`] in
/// format 3 and the legacy one in formats 1 and 2. HMAC is a pseudo-random
/// function as long as its key is secret, which is exactly what a counter
/// mode requires.
///
/// Each key is used **only once**, with a fresh salt: reusing a stream with
/// two different messages would reveal their exclusive or. The format of
/// [`seal`] guarantees this uniqueness by construction.
fn keystream_xor(label: &[u8], key: &[u8; 32], data: &mut [u8]) {
    let mut input = Vec::with_capacity(label.len() + 8);
    for (counter, chunk) in (0u64..).zip(data.chunks_mut(32)) {
        input.clear();
        input.extend_from_slice(label);
        input.extend_from_slice(&counter.to_le_bytes());
        let block = hmac_sha256(key, &input);
        for (o, k) in chunk.iter_mut().zip(block.iter()) {
            *o ^= k;
        }
    }
}

/// Constant-time comparison.
///
/// Comparing two authenticators with `==` leaks, through the response time,
/// the number of correct bytes — enough to rebuild them one byte at a
/// time.
pub fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

/// Zeroes a sensitive buffer, in a way the optimizer cannot remove.
///
/// An ordinary write whose result nobody reads is dead code in the eyes of
/// the compiler, and it removes it. `write_volatile` makes it mandatory. This
/// protects neither against a reader of RAM during execution, nor against a
/// page swapped to disk; it prevents a secret from surviving in a reused
/// heap, and then in a core dump.
pub fn wipe(buf: &mut [u8]) {
    for o in buf.iter_mut() {
        // Safe: each pointer comes from a valid element of the buffer.
        unsafe { std::ptr::write_volatile(o, 0) };
    }
}

/// Two independent keys derived from a passphrase.
///
/// Wiped when dropped: a wallet encryption key lying around in the heap is
/// worth as much as the passphrase itself.
struct Keys {
    encryption: [u8; 32],
    authentication: [u8; 32],
}

impl Drop for Keys {
    fn drop(&mut self) {
        wipe(&mut self.encryption);
        wipe(&mut self.authentication);
    }
}

fn derive_pbkdf2(passphrase: &[u8], salt: &[u8; 16], iterations: u32) -> Keys {
    // A single 64-byte derivation, cut in two. Deriving twice would double
    // the cost for the user without adding anything for the attacker.
    let mut raw = [0u8; 64];
    pbkdf2(passphrase, salt, iterations, &mut raw);
    let keys = split_keys(&raw);
    wipe(&mut raw);
    keys
}

/// The Argon2id derivation of the current format.
fn derive_argon2(passphrase: &[u8], salt: &[u8; 16], cost: Cost) -> Keys {
    let p = crate::argon2::Params {
        variant: crate::argon2::Variant::Id,
        memory_kib: cost.memory_kib,
        passes: cost.passes,
        lanes: 1,
    };
    let mut raw = crate::argon2::derive_key(p, passphrase, salt, &[], &[], 64);
    let mut buf = [0u8; 64];
    buf.copy_from_slice(&raw);
    let keys = split_keys(&buf);
    wipe(&mut raw);
    wipe(&mut buf);
    keys
}

fn split_keys(raw: &[u8; 64]) -> Keys {
    let mut encryption = [0u8; 32];
    let mut authentication = [0u8; 32];
    encryption.copy_from_slice(&raw[..32]);
    authentication.copy_from_slice(&raw[32..]);
    Keys {
        encryption,
        authentication,
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum SealError {
    /// The format is not recognized.
    InvalidFormat,
    /// The authenticator does not match: wrong passphrase, or altered data.
    /// The two are not told apart, deliberately.
    AuthenticationFailed,
    /// The header announces a number of iterations that no honest setting
    /// produces. Refused **before** the derivation, so without paying its
    /// cost.
    IterationsOutOfRange(u32),
    /// The header of the current format announces an Argon2id cost out of
    /// bounds. Refused the same way, before any derivation.
    CostOutOfRange { memory_kib: u32, passes: u32 },
}

impl std::fmt::Display for SealError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SealError::InvalidFormat => write!(f, "invalid sealed format"),
            SealError::AuthenticationFailed => write!(
                f,
                "wrong passphrase, or altered file\n  \
                 (both cases give the same message: telling one from the \
                 other would inform an attacker)"
            ),
            SealError::IterationsOutOfRange(n) => write!(
                f,
                "this file announces {n} iterations, above the ceiling of \
                 {MAX_ITERATIONS}: it has been altered"
            ),
            SealError::CostOutOfRange { memory_kib, passes } => write!(
                f,
                "this file announces {memory_kib} KiB and {passes} pass(es), out of \
                 bounds (8 to {MAX_MEMORY_KIB} KiB, 1 to {MAX_PASSES} passes): it has been altered"
            ),
        }
    }
}

/// Magic of format 1 (PBKDF2). Read, never written.
const MAGIC_V1: &[u8; 8] = crate::legacy::LEGACY_SEAL_V1_MAGIC;
/// Magic of format 2 (Argon2id, legacy keystream label). Read, never written.
const MAGIC_V2: &[u8; 8] = crate::legacy::LEGACY_SEAL_V2_MAGIC;
/// Magic of the current format, 3. Frozen: changing it would orphan existing
/// sealed files, including encrypted wallets.
const MAGIC_V3: &[u8; 8] = b"Q21SEAL3";

/// Keystream label of the current format. Frozen, for the same reason.
pub const KEYSTREAM_LABEL: &[u8] = b"Q21/keystream";

/// Ceiling on the number of iterations accepted on reading.
///
/// Fifty million PBKDF2-HMAC-SHA256 iterations represent about one minute on
/// a common processor: beyond that, no honest configuration, and an open
/// door to denial of service by simply rewriting four bytes.
pub const MAX_ITERATIONS: u32 = 50_000_000;

/// Encrypts then authenticates.
///
/// Format 3: `MAGIC_V3(8) || memory_kib(4) || passes(4) || salt(16) ||
/// ciphertext(n) || mac(32)`.
///
/// The authenticator covers **everything before it**, header included:
/// without that, an attacker could bring the cost down to nothing and turn
/// the protection into a formality.
///
/// The order is encrypt-**then**-authenticate: nothing is ever decrypted
/// before checking that it really comes from the holder of the passphrase.
pub fn seal(
    passphrase: &[u8],
    plaintext: &[u8],
    cost: Cost,
) -> Result<Vec<u8>, crate::rng::RngError> {
    let salt: [u8; 16] = crate::rng::bytes()?;
    let k = derive_argon2(passphrase, &salt, cost);

    let mut out = Vec::with_capacity(8 + 4 + 4 + 16 + plaintext.len() + 32);
    out.extend_from_slice(MAGIC_V3);
    out.extend_from_slice(&cost.memory_kib.to_le_bytes());
    out.extend_from_slice(&cost.passes.to_le_bytes());
    out.extend_from_slice(&salt);

    let ciphertext_start = out.len();
    out.extend_from_slice(plaintext);
    keystream_xor(KEYSTREAM_LABEL, &k.encryption, &mut out[ciphertext_start..]);

    let mac = hmac_sha256(&k.authentication, &out);
    out.extend_from_slice(&mac);
    Ok(out)
}

/// Is this content a sealed file?
///
/// Useful to warn the user *before* asking for their passphrase: a bare
/// prompt, with nothing announcing it, looks like a failure. We never guess
/// — either the file carries the magic, or it is not sealed.
pub fn is_sealed(content: &[u8]) -> bool {
    content.starts_with(MAGIC_V1) || content.starts_with(MAGIC_V2) || content.starts_with(MAGIC_V3)
}

/// Is this sealed content in the current format (3)?
pub fn is_current_format(content: &[u8]) -> bool {
    content.starts_with(MAGIC_V3)
}

/// Is this sealed content in format 1 (PBKDF2), to be resealed?
pub fn is_legacy_format(content: &[u8]) -> bool {
    content.starts_with(MAGIC_V1)
}

/// The Argon2id cost announced by the header of a sealed file in format 2
/// or 3.
///
/// `None` for any other content — a plaintext file, or format 1, which has
/// no Argon2 cost. The value is read **before** being authenticated, as
/// in [`unseal`]: it is only used to decide on a reseal once the passphrase
/// has been verified, never to grant anything.
pub fn stored_cost(content: &[u8]) -> Option<Cost> {
    if !(content.starts_with(MAGIC_V2) || content.starts_with(MAGIC_V3)) || content.len() < 16 {
        return None;
    }
    Some(Cost {
        memory_kib: u32::from_le_bytes([content[8], content[9], content[10], content[11]]),
        passes: u32::from_le_bytes([content[12], content[13], content[14], content[15]]),
    })
}

/// Is this sealed content protected by less than the default cost?
///
/// # The defect this closes
///
/// The MAC covers the header: a third party without the passphrase cannot
/// lower the cost. But a file sealed at 8 KiB and one pass — by another tool,
/// a modified version, a test option — opened in forty microseconds without
/// a word, and was never resealed: the user believed their file was behind
/// 64 MiB of Argon2id. A floor would not have been enough — refusing to open
/// a legitimate wallet would be worse — but it must be said, and the file
/// resealed at the default cost on the first opening.
///
/// Format 1 (PBKDF2) is **always** below the default: it has no memory
/// hardness at all, which is why it is resealed.
pub fn is_below_default_cost(content: &[u8]) -> bool {
    if is_legacy_format(content) {
        return true;
    }
    match stored_cost(content) {
        Some(c) => c.memory_kib < DEFAULT_COST.memory_kib || c.passes < DEFAULT_COST.passes,
        None => false,
    }
}

/// Verifies then decrypts.
pub fn unseal(passphrase: &[u8], sealed: &[u8]) -> Result<Vec<u8>, SealError> {
    // --- A truncated file must not be distinguishable from a wrong passphrase.
    //
    // The documentation of this module promised that both cases give the same
    // message; an audit showed they did not. A truncation returned
    // `InvalidFormat`, a wrong passphrase `AuthenticationFailed`: enough to
    // learn, by watching the messages, whether the passphrase tried was the
    // right one on a file one had just damaged oneself.
    //
    // The distinction is kept only where it informs the user without telling
    // an attacker anything: **the magic**. If it is absent, this file is not a
    // Q21 wallet, and saying so informs nobody. If it is present but the rest
    // is unreadable, it is the same message as a wrong passphrase.
    if sealed.len() < 8 {
        return Err(SealError::InvalidFormat);
    }
    if &sealed[..8] == MAGIC_V3 {
        return unseal_argon2(passphrase, sealed, KEYSTREAM_LABEL);
    }
    if &sealed[..8] == MAGIC_V2 {
        return unseal_argon2(passphrase, sealed, crate::legacy::LEGACY_KEYSTREAM_LABEL);
    }
    if &sealed[..8] != MAGIC_V1 {
        return Err(SealError::InvalidFormat);
    }
    if sealed.len() < 8 + 4 + 16 + 32 {
        return Err(SealError::AuthenticationFailed);
    }
    let iterations = u32::from_le_bytes([sealed[8], sealed[9], sealed[10], sealed[11]]);
    if iterations == 0 {
        return Err(SealError::AuthenticationFailed);
    }
    // --- The number of iterations is authenticated, but it is **read before**
    //     it is. This is unavoidable: the key is needed to check the MAC, and
    //     this number is needed to derive the key.
    //
    // An audit used it: four bytes written into `wallet.dat` — not the
    // passphrase, not the seed, just the header — imposed up to 2^32-1
    // PBKDF2 iterations. Hours of computation before any rejection, and a
    // wallet that simply seems to no longer open.
    //
    // So the bound is applied **before** the derivation, on a value we are
    // not yet entitled to believe. It is wide: it lets every legitimate
    // setting through, and cuts off the absurd.
    if iterations > MAX_ITERATIONS {
        return Err(SealError::IterationsOutOfRange(iterations));
    }
    let mut salt = [0u8; 16];
    salt.copy_from_slice(&sealed[12..28]);

    let (body, received_mac) = sealed.split_at(sealed.len() - 32);
    let k = derive_pbkdf2(passphrase, &salt, iterations);

    // Verification BEFORE any decryption.
    let mac = hmac_sha256(&k.authentication, body);
    if !constant_time_eq(&mac, received_mac) {
        return Err(SealError::AuthenticationFailed);
    }

    let mut plaintext = body[28..].to_vec();
    keystream_xor(
        crate::legacy::LEGACY_KEYSTREAM_LABEL,
        &k.encryption,
        &mut plaintext,
    );
    Ok(plaintext)
}

/// Formats 2 and 3, which differ only by the keystream label. Same
/// discipline as format 1: the cost is read before being authenticated — it
/// has to be, to derive the key — so it is bounded before any derivation; the
/// MAC is verified before any decryption.
fn unseal_argon2(passphrase: &[u8], sealed: &[u8], label: &[u8]) -> Result<Vec<u8>, SealError> {
    const HEADER: usize = 8 + 4 + 4 + 16;
    if sealed.len() < HEADER + 32 {
        return Err(SealError::AuthenticationFailed);
    }
    let memory_kib = u32::from_le_bytes([sealed[8], sealed[9], sealed[10], sealed[11]]);
    let passes = u32::from_le_bytes([sealed[12], sealed[13], sealed[14], sealed[15]]);
    if !(8..=MAX_MEMORY_KIB).contains(&memory_kib) || !(1..=MAX_PASSES).contains(&passes) {
        return Err(SealError::CostOutOfRange { memory_kib, passes });
    }
    let mut salt = [0u8; 16];
    salt.copy_from_slice(&sealed[16..32]);

    let (body, received_mac) = sealed.split_at(sealed.len() - 32);
    let k = derive_argon2(passphrase, &salt, Cost { memory_kib, passes });
    let mac = hmac_sha256(&k.authentication, body);
    if !constant_time_eq(&mac, received_mac) {
        return Err(SealError::AuthenticationFailed);
    }
    let mut plaintext = body[HEADER..].to_vec();
    keystream_xor(label, &k.encryption, &mut plaintext);
    Ok(plaintext)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hex(o: &[u8]) -> String {
        o.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// A sealed file below the default cost is recognized as such; one at
    /// the default, or above, is not; format 1 always is.
    #[test]
    fn sealed_below_default_cost_is_recognized() {
        let weak = seal(
            b"p",
            b"x",
            Cost {
                memory_kib: 8,
                passes: 1,
            },
        )
        .unwrap();
        assert_eq!(
            stored_cost(&weak),
            Some(Cost {
                memory_kib: 8,
                passes: 1
            })
        );
        assert!(is_below_default_cost(&weak));
        // Enough memory, not enough passes: still below the default.
        let passes = seal(
            b"p",
            b"x",
            Cost {
                memory_kib: DEFAULT_COST.memory_kib,
                passes: 1,
            },
        )
        .unwrap();
        assert!(is_below_default_cost(&passes));
        // The default cost itself: nothing to reseal.
        let default = seal(b"p", b"x", DEFAULT_COST).unwrap();
        assert_eq!(stored_cost(&default), Some(DEFAULT_COST));
        assert!(!is_below_default_cost(&default));
        // Plaintext content has no cost, and is not "below the default".
        assert_eq!(stored_cost(b"seed=00"), None);
        assert!(!is_below_default_cost(b"seed=00"));
        // Format 1 always needs resealing.
        let mut old = Vec::new();
        old.extend_from_slice(MAGIC_V1);
        old.extend_from_slice(&1_000u32.to_le_bytes());
        old.extend_from_slice(&[7u8; 16]);
        assert!(is_legacy_format(&old));
        assert!(is_below_default_cost(&old));
    }

    // -----------------------------------------------------------------------
    // Official RFC 4231 vectors
    // -----------------------------------------------------------------------
    //
    // These vectors validate at once HMAC **and** the SHA-256 implementation
    // it rests on. Passing them by accident is impossible.

    #[test]
    fn hmac_rfc4231_case_1() {
        let key = [0x0bu8; 20];
        let mac = hmac_sha256(&key, b"Hi There");
        assert_eq!(
            hex(&mac),
            "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
        );
    }

    #[test]
    fn hmac_rfc4231_case_2() {
        let mac = hmac_sha256(b"Jefe", b"what do ya want for nothing?");
        assert_eq!(
            hex(&mac),
            "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"
        );
    }

    /// Case 3: key and message of 0xaa / 0xdd bytes.
    #[test]
    fn hmac_rfc4231_case_3() {
        let key = [0xaau8; 20];
        let msg = [0xddu8; 50];
        let mac = hmac_sha256(&key, &msg);
        assert_eq!(
            hex(&mac),
            "773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe"
        );
    }

    /// Case 6: key **longer than a block**, hence hashed first. It is the
    /// easiest branch to get wrong in a home-made implementation.
    #[test]
    fn hmac_rfc4231_case_6_long_key() {
        let key = [0xaau8; 131];
        let mac = hmac_sha256(
            &key,
            b"Test Using Larger Than Block-Size Key - Hash Key First",
        );
        assert_eq!(
            hex(&mac),
            "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54"
        );
    }

    // -----------------------------------------------------------------------
    // PBKDF2
    // -----------------------------------------------------------------------

    /// Widely published PBKDF2-HMAC-SHA256 vector (RFC 7914, section 11).
    #[test]
    fn pbkdf2_known_vector() {
        let mut out = [0u8; 64];
        pbkdf2(b"passwd", b"salt", 1, &mut out);
        assert_eq!(
            hex(&out),
            "55ac046e56e3089fec1691c22544b605f94185216dde0465e68b9d57c20dacbc\
             49ca9cccf179b645991664b39d77ef317c71b845b1e30bd509112041d3a19783"
        );
    }

    #[test]
    fn pbkdf2_changes_with_salt_and_iterations() {
        let mut a = [0u8; 32];
        let mut b = [0u8; 32];
        let mut c = [0u8; 32];
        pbkdf2(b"pwd", b"salt-a", 1_000, &mut a);
        pbkdf2(b"pwd", b"salt-b", 1_000, &mut b);
        pbkdf2(b"pwd", b"salt-a", 1_001, &mut c);
        assert_ne!(a, b, "the salt must change the output");
        assert_ne!(a, c, "the number of iterations must change the output");
    }

    #[test]
    fn pbkdf2_is_deterministic() {
        let mut a = [0u8; 40];
        let mut b = [0u8; 40];
        pbkdf2(b"passphrase", b"salt", 500, &mut a);
        pbkdf2(b"passphrase", b"salt", 500, &mut b);
        assert_eq!(a, b);
    }

    // -----------------------------------------------------------------------
    // Sealing
    // -----------------------------------------------------------------------

    #[test]
    fn seal_round_trip() {
        let plaintext = b"very secret thirty-two byte seed";
        let s = seal(b"my passphrase", plaintext, TEST_COST).unwrap();
        assert_eq!(unseal(b"my passphrase", &s).unwrap(), plaintext);
    }

    #[test]
    fn a_wrong_passphrase_is_refused() {
        let s = seal(b"right", b"secret", TEST_COST).unwrap();
        assert_eq!(unseal(b"wrong", &s), Err(SealError::AuthenticationFailed));
    }

    /// The ciphertext must never give the plaintext away.
    #[test]
    fn plaintext_does_not_appear_in_sealed_output() {
        let plaintext = b"RECOGNIZABLE-PATTERN-0123456789";
        let s = seal(b"passphrase", plaintext, TEST_COST).unwrap();
        assert!(
            !s.windows(plaintext.len()).any(|f| f == plaintext),
            "the plaintext appears as is in the sealed output"
        );
    }

    /// Two seals of the same plaintext with the same passphrase must differ:
    /// otherwise, an observer learns that nothing changed.
    #[test]
    fn two_seals_of_the_same_plaintext_differ() {
        let a = seal(b"passphrase", b"identical", TEST_COST).unwrap();
        let b = seal(b"passphrase", b"identical", TEST_COST).unwrap();
        assert_ne!(a, b, "the salt must be fresh for every seal");
        assert_eq!(unseal(b"passphrase", &a).unwrap(), b"identical");
        assert_eq!(unseal(b"passphrase", &b).unwrap(), b"identical");
    }

    /// A byte modified **anywhere** must make opening fail, in particular in
    /// the header: that is what prevents bringing the number of iterations
    /// down to one.
    #[test]
    fn a_modified_byte_makes_opening_fail() {
        // The test cost: this test performs one derivation per byte of the
        // sealed output, and it is the property being checked, not the cost
        // of the derivation.
        let s = seal(b"passphrase", b"well-kept secret", TEST_COST).unwrap();
        for pos in 0..s.len() {
            let mut altered = s.clone();
            altered[pos] ^= 0x01;
            assert!(
                unseal(b"passphrase", &altered).is_err(),
                "byte {pos} could be modified without being detected"
            );
        }
    }

    #[test]
    fn a_truncated_seal_is_refused() {
        let s = seal(b"passphrase", b"secret", TEST_COST).unwrap();
        for n in 0..s.len() {
            assert!(unseal(b"passphrase", &s[..n]).is_err());
        }
    }

    /// A sealed file in format 1 (PBKDF2) still opens: nobody must lose
    /// access to their wallet because the derivation changed. It is
    /// recognized as old, so that it gets resealed.
    #[test]
    fn a_seal_in_the_old_format_still_opens() {
        // Exact reproduction of the format 1 `seal`, with a fixed salt.
        let passphrase = b"passphrase from before";
        let plaintext = b"seed=deadbeef\nnext_index=3\n";
        let iterations = 1_000u32;
        let salt = [7u8; 16];
        let k = derive_pbkdf2(passphrase, &salt, iterations);
        let mut old = Vec::new();
        old.extend_from_slice(MAGIC_V1);
        old.extend_from_slice(&iterations.to_le_bytes());
        old.extend_from_slice(&salt);
        let start = old.len();
        old.extend_from_slice(plaintext);
        keystream_xor(
            crate::legacy::LEGACY_KEYSTREAM_LABEL,
            &k.encryption,
            &mut old[start..],
        );
        let mac = hmac_sha256(&k.authentication, &old);
        old.extend_from_slice(&mac);

        assert!(is_sealed(&old));
        assert!(is_legacy_format(&old));
        assert_eq!(unseal(passphrase, &old).unwrap(), plaintext);
        assert!(unseal(b"other", &old).is_err());

        // And the current format is not "old".
        let new = seal(passphrase, plaintext, TEST_COST).unwrap();
        assert!(is_sealed(&new));
        assert!(!is_legacy_format(&new));
        assert_eq!(unseal(passphrase, &new).unwrap(), plaintext);
    }

    /// A wallet sealed by 0.3.x (format 2: Argon2id, legacy keystream label)
    /// still opens, and what is sealed now is format 3. Moving a file from one
    /// format to the other by rewriting its magic fails: the MAC covers it.
    #[test]
    fn a_seal_in_format_2_still_opens_and_new_seals_are_format_3() {
        let passphrase = b"passphrase from 0.3";
        let plaintext = b"seed=deadbeef\nnext_index=3\nserial=4\n";
        let salt = [9u8; 16];
        let k = derive_argon2(passphrase, &salt, TEST_COST);
        let mut v2 = Vec::new();
        v2.extend_from_slice(MAGIC_V2);
        v2.extend_from_slice(&TEST_COST.memory_kib.to_le_bytes());
        v2.extend_from_slice(&TEST_COST.passes.to_le_bytes());
        v2.extend_from_slice(&salt);
        let start = v2.len();
        v2.extend_from_slice(plaintext);
        keystream_xor(
            crate::legacy::LEGACY_KEYSTREAM_LABEL,
            &k.encryption,
            &mut v2[start..],
        );
        let mac = hmac_sha256(&k.authentication, &v2);
        v2.extend_from_slice(&mac);

        assert!(is_sealed(&v2));
        assert!(!is_legacy_format(&v2));
        assert_eq!(stored_cost(&v2), Some(TEST_COST));
        assert_eq!(unseal(passphrase, &v2).unwrap(), plaintext);
        assert_eq!(unseal(b"other", &v2), Err(SealError::AuthenticationFailed));

        let v3 = seal(passphrase, plaintext, TEST_COST).unwrap();
        assert_eq!(&v3[..8], MAGIC_V3);
        assert_eq!(stored_cost(&v3), Some(TEST_COST));
        assert_eq!(unseal(passphrase, &v3).unwrap(), plaintext);

        let mut relabeled = v2.clone();
        relabeled[..8].copy_from_slice(MAGIC_V3);
        assert_eq!(
            unseal(passphrase, &relabeled),
            Err(SealError::AuthenticationFailed)
        );
        let mut relabeled = v3.clone();
        relabeled[..8].copy_from_slice(MAGIC_V2);
        assert_eq!(
            unseal(passphrase, &relabeled),
            Err(SealError::AuthenticationFailed)
        );
    }

    /// The two keystream labels give two different streams: a file sealed
    /// under one cannot be read under the other.
    #[test]
    fn the_two_keystream_labels_differ() {
        let key = [3u8; 32];
        let mut a = [0u8; 64];
        let mut b = [0u8; 64];
        keystream_xor(KEYSTREAM_LABEL, &key, &mut a);
        keystream_xor(crate::legacy::LEGACY_KEYSTREAM_LABEL, &key, &mut b);
        assert_ne!(a, b);
    }

    /// A cost rewritten in the header is refused before any derivation: an
    /// attacker who writes eight bytes must not be able to impose a gibibyte
    /// of computation before any rejection.
    #[test]
    fn an_out_of_range_cost_is_refused_before_deriving() {
        let s = seal(b"passphrase", b"secret", TEST_COST).unwrap();
        let mut memory = s.clone();
        memory[8..12].copy_from_slice(&u32::MAX.to_le_bytes());
        let t = std::time::Instant::now();
        assert!(matches!(
            unseal(b"passphrase", &memory),
            Err(SealError::CostOutOfRange { .. })
        ));
        assert!(t.elapsed() < std::time::Duration::from_millis(50));

        let mut passes = s.clone();
        passes[12..16].copy_from_slice(&1_000u32.to_le_bytes());
        assert!(matches!(
            unseal(b"passphrase", &passes),
            Err(SealError::CostOutOfRange { .. })
        ));
    }

    #[test]
    fn an_arbitrary_file_is_not_sealed() {
        assert_eq!(
            unseal(b"passphrase", b"this is not a sealed file at all"),
            Err(SealError::InvalidFormat)
        );
    }

    #[test]
    fn constant_time_comparison_is_correct() {
        assert!(constant_time_eq(b"abc", b"abc"));
        assert!(!constant_time_eq(b"abc", b"abd"));
        assert!(!constant_time_eq(b"abc", b"ab"));
        assert!(constant_time_eq(b"", b""));
    }
}
